In [2]:
import pandas as pd
from io import StringIO

In [3]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Project Coordinator", "title2": "Project Manager"}]}'
df = pd.read_json(StringIO(Data))

In [4]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Project Coordinator', 'title2': 'P..."

In [5]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Project Coordinator","title2":"Project Manager"}}}'

In [6]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Project Coordinator","title2":"Project Manager"}}}'

In [7]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Project Coordinator","title2":"Project Manager"}}]'

In [8]:
## Reading from web url (csv)
df_wine = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data", header=None)
df_wine

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [9]:
%pip install lxml
%pip install html5lib
%pip install bs4

Requirement already satisfied: lxml in d:\my learning\python_krish-naik\my_learning\venv\lib\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: html5lib in d:\my learning\python_krish-naik\my_learning\venv\lib\site-packages (1.1)
Requirement already satisfied: six>=1.9 in d:\my learning\python_krish-naik\my_learning\venv\lib\site-packages (from html5lib) (1.16.0)
Requirement already satisfied: webencodings in d:\my learning\python_krish-naik\my_learning\venv\lib\site-packages (from html5lib) (0.5.1)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: bs4 in d:\my learning\python_krish-naik\my_learning\venv\lib\site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in d:\my learning\python_krish-naik\my_learning\venv\lib\site-packages (from bs4) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in d:\my learning\python_krish-naik\my_learning\venv\lib\site-packages (from beautifulsoup4->bs4) (2.5)
Note: you may need to restart the kernel to use updated packages.

In [11]:
html_url = 'https://www.fdic.gov/bank/individual/failed/banklist.html'
df_html = pd.read_html(html_url)
df_html

[                               Bank Name               City          State  \
 0     The First National Bank of Lindsay            Lindsay       Oklahoma
 1  Republic First Bank dba Republic Bank       Philadelphia   Pennsylvania
 2                          Citizens Bank           Sac City           Iowa
 3               Heartland Tri-State Bank            Elkhart         Kansas
 4                    First Republic Bank      San Francisco     California
 5                         Signature Bank           New York       New York
 6                    Silicon Valley Bank        Santa Clara     California
 7                      Almena State Bank             Almena         Kansas
 8             First City Bank of Florida  Fort Walton Beach        Florida
 9                   The First State Bank      Barboursville  West Virginia

     Cert                 Aquiring Institution      Closing Date  \
 0   4134   First Bank & Trust Co., Duncan, OK  October 18, 2024
 1  27332    Fulton Bank, National Association    April 26, 2024
 2   8758            Iowa Trust & Savings Bank  November 3, 2023
 3  25851               Dream First Bank, N.A.     July 28, 2023
 4  59017            JPMorgan Chase Bank, N.A.       May 1, 2023
 5  57053                  Flagstar Bank, N.A.    March 12, 2023
 6  24735  First Citizens Bank & Trust Company    March 10, 2023
 7  15426                          Equity Bank  October 23, 2020
 8  16748            United Fidelity Bank, fsb  October 16, 2020
 9  14361                       MVB Bank, Inc.     April 3, 2020

    Fund  Sort ascending
 0                 10547
 1                 10546
 2                 10545
 3                 10544
 4                 10543
 5                 10540
 6                 10539
 7                 10538
 8                 10537
 9                 10536  ]

In [14]:
df_html[1]

IndexError: list index out of range

In [25]:
url = "https://en.wikipedia.org/wiki/Mobile_country_code"
url_data = pd.read_html(url, match='Country', header=0)[0]
url_data

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [28]:
%pip install openpyxl
excel_data = pd.read_excel('sample_data.xlsx')
excel_data

Requirement already satisfied: openpyxl in d:\my learning\python_krish-naik\my_learning\venv\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in d:\my learning\python_krish-naik\my_learning\venv\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

     name  age
0      Kp   31
1  Shravs   29
2    Nyra    4
3   Datta    1

In [32]:
excel_data.to_pickle('df_pickle')

In [33]:
pd.read_pickle('df_pickle')

     name  age
0      Kp   31
1  Shravs   29
2    Nyra    4
3   Datta    1